### ISSUE TITLE
revdep check on wesanderson

### ISSUE THREAD

**Issue by karthik** [nhejazi/biotmle#39]
👋 @nhejazi 
Just wanted to check if you're having any build issues with this package. I find that `wesanderson` fails on a revdep check here. But I suspect it was an issue earlier from using `Zissou` instead of `Zissou1`.

I see that this has been replaced with: https://github.com/nhejazi/biotmle/blob/9349978d7a1b341e9e19e6bc5bd0ff0f8e828dd4/R/plots.R#L107

If this is correct, I'll ignore the failed check and proceed. Please advise. 

Current error is:

```r
   > heatmap_ic(x = limmaTMLEout, design = design, FDRcutoff = 0.05,
    +            top = 15)
    Error in wes_palette("Zissou", 100, type = "continuous") : 
      Palette not found.
    Calls: heatmap_ic -> wes_palette
    Execution halted
```

Thanks for your help :pray:

**Comment by nhejazi** [comment]
Hello @karthik -- thanks for checking in!

As of 0e25b8a (the latest on `master`), I am not seeing any check failures for this package, whether locally or on CI, with both travis and appveyor builds passing for R release and devel. Over the recent development history of the package, I've changed colorschemes within `wesanderson` -- both due to changes in preference and to be consistent with the naming of colorschemes wrt to the current CRAN release of `wesanderson` (note that `biotmle` is limited to using the CRAN release due to restrictions in package dependencies based on Bioconductor policies). I'm not sure any of this information helps with the revdep check but at least confirming that I'm not seeing build failures.

**Comment by karthik** [comment]
Perfect, thanks @nhejazi!
