### ISSUE TITLE
Error in superheat:

### ISSUE THREAD

**Issue by dcpattie** [nhejazi/biotmle#61]
Hello, I'm following your excellent biomarker pipeline and ran across an error with the heatmap/dendrogram command (see below).

```
heatmap_ic(x = limmaTMLEout,
+            row.dendrogram = TRUE,
+            clustering.method = "hierarchical",
+            design = design, FDRcutoff = 1.0, top = 10)
**Error in superheat::superheat(as.matrix(biomarkerTMLEout_top), row.dendrogram = TRUE,  : 
  formal argument "row.dendrogram" matched by multiple actual arguments**
```

I installed the superheat package so I'm not sure where the error is coming from?

**Comment by nhejazi** [comment]
Thanks for reporting this. Just a few clarifications: What versions of the `superheat` and `biotmle` are being used in the example? (e.g., CRAN installation of `superheat` v0.1.0; Bioconductor 3.8 installation of `biotmle` v1.6.0). I recall seeing this bug myself at some point during testing but thought it had been resolved on the version of `biotmle` on the `master` branch.

**Comment by dcpattie** [comment]
Hi Nima,

Many thanks for the reply.  I'm away from my home computer but if I recall
correctly I used 3.8 for both biotmle and superheat.  I can send you a
screenshot of my RStudio console when I get home later today.

Very respectfully
David

**Comment by nhejazi** [comment]
After replacing the development version of `biotmle` with v1.6.0 from Bioconductor v3.8, I've been able to replicate this behavior. Please note that this is not technically a bug in either `biotmle` or `superheat` but due to a change in the `heatmap_ic` function. Note that the version of the function in v1.6.0 ([here](https://github.com/nhejazi/biotmle/blob/RELEASE_3_8/R/plots.R#L209-L216)) of the package forces the argument `row.dendrogram = TRUE` in its call to `superheat`; however, in the development version ([here](https://github.com/nhejazi/biotmle/blob/master/R/plots.R#L223-L229)), that setting has been removed, making it so that `row.dendrogram = TRUE` must be manually passed to `superheat` via `heatmap_ic`.

The easiest way to repair this, while still using v1.6.0 of `biotmle` from Bioconductor v3.8, would be to amend your example as follows
```r
heatmap_ic(x = limmaTMLEout,
+            clustering.method = "hierarchical",
+            design = design, FDRcutoff = 1.0, top = 10)
```

I'm going to go ahead and close this issue but feel free to re-open should the problem persist.
