### ISSUE TITLE
Error in eif

### ISSUE THREAD

**Issue by dcpattie** [nhejazi/biotmle#62]
I don't think this is a dealbreaker but I did come across the following error:

> head(eif(rnaseqTMLEout)$E[, seq_len(6)])
Error in eif(rnaseqTMLEout) : could not find function "eif"

**Comment by nhejazi** [comment]
This problem arises due to the same reason explained in #63 --- that is, v1.7.2 of `biotmle` on GitHub `master` exports several accessor functions (for convenience) that are not available in v1.6.0 of `biotmle` currently available from the Bioconductor 3.8 release. These will be available upon the release of Bioconductor 3.9 in April/May 2019; however, for now, they will remain only available via the development version of `biotmle` available on the branch `master`. Note that `eif` accessor function is defined simply as a call to the `tmleOut` slot of a `bioTMLE` object (see [here](https://github.com/nhejazi/biotmle/blob/master/R/biotmle-class.R#L81-L84)). To extract the same information with your current version of `biotmle`, please use
```r
head(rnaseqTMLEout@tmleOut$E[, seq_len(6)])
```

Feel free to re-open this issue if this does not resolve your issue. Hope this helps.
